# GitHub Copilot Coding Agent Configuration
# This file configures the Copilot Coding Agent for the NIJA Bot repository

# Startup script location
startup_script: /app/start_all.sh

# Build command (if using Dockerfile)
build_command: docker build -t nija-bot .

# Required secrets
required_secrets:
  - GITHUB_PAT
  - COINBASE_API_KEY
  - COINBASE_API_SECRET
  - COINBASE_PEM_CONTENT

# PEM secrets mount location
secrets_mount:
  coinbase_pem: /opt/railway/secrets/coinbase.pem

# Environment variables
environment:
  PORT: 5000
  WEB_CONCURRENCY: 1
