#!/bin/bash
# Quick check - Is NIJA selling and making profit?

echo "================================================================================"
echo "🔍 NIJA SELLING & PROFIT QUICK CHECK"
echo "================================================================================"
echo ""

# Run the verification script
python3 verify_nija_selling_now.py

echo ""
echo "================================================================================"
echo "📊 NIJA CONFIGURATION (FROM CODE)"
echo "================================================================================"
echo ""
echo "Selling Triggers:"
echo "  ✅ Take Profit: +6% (positions auto-sell when hit)"
echo "  ✅ Stop Loss: -2% (positions auto-close to protect capital)"
echo "  ✅ Trailing Stop: Locks in 98% of gains"
echo "  ✅ Opposite Signal: Exits when trend reverses"
echo ""
echo "Position Limits:"
echo "  • Max concurrent: 8 positions"
echo "  • One position per symbol"
echo ""
echo "Selling Logic Status:"
echo "  ✅ Implemented in: bot/trading_strategy.py lines 680-900"
echo "  ✅ Manages positions every scan cycle"
echo "  ✅ Retry logic: 3 attempts per sell order"
echo "  ✅ Handles partial fills"
echo ""
echo "================================================================================"
echo "🚂 RAILWAY DEPLOYMENT CHECK"
echo "================================================================================"
echo ""
echo "To verify bot is running:"
echo "  1. Visit: https://railway.app"
echo "  2. Select your NIJA project"
echo "  3. Check 'Deployments' → Latest deployment"
echo "  4. View logs for:"
echo "     • '📊 Managing X open position(s)...'"
echo "     • '🔄 Closing [SYMBOL] position: [reason]'"
echo "     • '✅ Position closed with PROFIT: \$X.XX'"
echo ""
echo "Expected sell messages in logs:"
echo "  • 'Take profit hit @ \$X.XX'"
echo "  • 'Trailing stop hit @ \$X.XX'"
echo "  • 'Stop loss hit @ \$X.XX'"
echo "  • 'Order status = filled'"
echo ""
echo "================================================================================"
echo "💡 NEXT ACTIONS"
echo "================================================================================"
echo ""
echo "If no sells happening:"
echo "  1. Positions may not have hit +6% yet (need time)"
echo "  2. Check if bot is running (Railway logs)"
echo "  3. Verify positions are in Advanced Trade (not Consumer)"
echo ""
echo "If Consumer wallet has crypto:"
echo "  • Run: python3 enable_nija_profit.py"
echo "  • This liquidates Consumer crypto and transfers to Advanced Trade"
echo ""
echo "If you need to force-sell everything:"
echo "  • Run: python3 direct_sell.py"
echo "  • Manual emergency liquidation"
echo ""
echo "================================================================================"
