FROM python:3.11-slim

# Install git and redis-cli for runtime diagnostics
RUN apt-get update && apt-get install -y git redis-tools && rm -rf /var/lib/apt/lists/*

# Create non-root user for security
RUN groupadd -r nija && useradd -r -g nija -u 1000 nija

# Set working directory
WORKDIR /app

# Copy requirements first for better Docker layer caching
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Explicitly copy runtime/preflight scripts into the image.
COPY scripts/ scripts/

# Copy application code
COPY . .

# Fail the image build immediately if entrypoint Python files or startup guards
# are syntactically invalid.
RUN python -m py_compile \
        /app/main.py \
        /app/bot.py \
        /app/prebot_writer_authority_bootstrap.py \
        /app/import_hook_recursion_shield_patch.py \
        /app/disconnected_broker_execution_guard_patch.py

# Install startup guards before sitecustomize executes. The alphabetically-first
# pre-bot hook acquires the canonical Redis writer lease only for NIJA's live
# main process; health checks, builds, tests and python -c subprocesses are skipped.
# Later hooks can therefore never observe a live process without fencing lineage.
RUN python -c "import pathlib, site; root = pathlib.Path(site.getsitepackages()[0]); p0 = root / '000_nija_prebot_writer_authority.pth'; p0.write_text('import prebot_writer_authority_bootstrap as _nija_prebot_writer; _nija_prebot_writer.install()\\n', encoding='utf-8'); p1 = root / 'nija_import_hook_recursion_shield.pth'; p1.write_text('import import_hook_recursion_shield_patch as _nija_shield; _nija_shield.install_import_hook()\\n', encoding='utf-8'); p2 = root / 'nija_disconnected_broker_execution_guard.pth'; p2.write_text('import disconnected_broker_execution_guard_patch as _nija_broker_guard; _nija_broker_guard.install_import_hook()\\n', encoding='utf-8'); assert p0.is_file() and p1.is_file() and p2.is_file()"

# Ensure Redis connectivity and production bootstrap scripts are present and executable.
RUN test -f /app/scripts/redis_connectivity_check.sh && \
    test -f /app/scripts/production_bootstrap.sh && \
    test -f /app/scripts/render_entrypoint.sh && \
    chmod +x /app/scripts/redis_connectivity_check.sh \
             /app/scripts/production_bootstrap.sh \
             /app/scripts/render_entrypoint.sh && \
    if [ -f /app/scripts/debug_startup_safe_mode.sh ]; then chmod +x /app/scripts/debug_startup_safe_mode.sh; fi

# Make other scripts executable when present in build context
RUN if [ -d /app/scripts ]; then chmod +x /app/scripts/*.sh || true; fi

# Render translates service environment variables into Docker build arguments.
# Declare Render's documented provenance variables so build-time version metadata
# can be generated without depending on a .git directory in the final image.
ARG GIT_BRANCH=""
ARG GIT_COMMIT=""
ARG RENDER_GIT_BRANCH=""
ARG RENDER_GIT_COMMIT=""
ARG RENDER_SERVICE_ID=""
ARG RENDER_SERVICE_NAME=""

# Provider-neutral portability fallbacks.
ARG RAILWAY_GIT_BRANCH=""
ARG RAILWAY_GIT_COMMIT_SHA=""
ARG RAILWAY_DEPLOYMENT_ID=""
ARG RAILWAY_ENVIRONMENT_NAME=""
ARG BUILD_TIMESTAMP=""

# Keep explicit values available at runtime; .env.build supplies the resolved
# Render/Git fallback generated by inject_git_metadata.sh.
ENV GIT_BRANCH=${GIT_BRANCH}
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_TIMESTAMP=${BUILD_TIMESTAMP}

# Generate traceable version metadata and fail the image build if generation fails.
RUN ./inject_git_metadata.sh

# Redirect candlelite config to a writable /tmp path so the okx SDK never
# tries to write SETTINGS.config into the read-only site-packages directory.
# This must be an ENV directive (not set in Python) so the variable is present
# before any Python import runs.
ENV CANDLELITE_CONFIG_DIR=/tmp/candlelite

# Create necessary directories and set permissions
RUN mkdir -p /app/cache /app/data /app/logs /tmp/candlelite && \
    chown -R nija:nija /app /tmp/candlelite

# Switch to non-root user
USER nija

# Security: Drop all capabilities and run as non-root
# Health check endpoint - use liveness probe
HEALTHCHECK --interval=30s --timeout=30s --start-period=300s --retries=5 \
    CMD python -c "import requests; requests.get('http://localhost:5000/healthz', timeout=10)" || exit 1

# Default command: resolve Render deployment provenance and guards before start.sh.
CMD ["bash", "scripts/production_bootstrap.sh"]
