#!/bin/bash
# Run recovery steps 1, 2, and 4

echo "=========================================="
echo "STEP 1: CHECK YOUR CRYPTO HOLDINGS"
echo "=========================================="
echo ""
python3 show_holdings.py

echo ""
echo ""
echo "=========================================="
echo "STEP 2: SELL ALL POSITIONS"
echo "=========================================="
echo ""
echo "⚠️  This will liquidate all crypto and recover USD"
echo ""
python3 sell_all_positions.py

echo ""
echo ""
echo "=========================================="
echo "STEP 4: WHEN READY TO TRADE AGAIN"
echo "=========================================="
echo ""
echo "💡 IMPORTANT INSTRUCTIONS:"
echo ""
echo "1. Deposit \$50-100 to Coinbase Advanced Trade"
echo "   (NOT \$5 - that will fail again!)"
echo ""
echo "2. Verify bot settings are updated:"
echo "   - Minimum position: \$10.00 ✅"
echo "   - Trade cooldown: 30 seconds ✅"
echo ""
echo "3. Monitor first 10 trades carefully"
echo "   - Each trade should be \$10-20"
echo "   - Should NOT drain account instantly"
echo ""
echo "4. Track profitability:"
echo "   - Fees should be < 1% per trade"
echo "   - Positions should have room to manage"
echo ""
echo "=========================================="
echo "✅ RECOVERY PROCESS COMPLETE"
echo "=========================================="
