name: CI — Prebuild checks & poetry install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x ./scripts/prebuild-check.sh

      - name: Run prebuild checks
        run: ./scripts/prebuild-check.sh

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: python -m pip install --upgrade pip && pip install "poetry==1.7.1"

      - name: Install dependencies (repo root)
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --no-dev
