#!/usr/bin/env python3
"""NIJA mobile-store release gate.

Checks repository state that can be validated before Apple/Google submission.
The Android Gradle project is generated by Capacitor, so absence is reported as a
non-release-ready condition when --strict is used. Once generated, both
compileSdk and targetSdk must be API 36 or higher for the August 31, 2026
Google Play requirement.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANDROID_CANDIDATES = [
    ROOT / "android" / "app" / "build.gradle",
    ROOT / "android" / "app" / "build.gradle.kts",
    ROOT / "mobile" / "android" / "app" / "build.gradle",
    ROOT / "mobile" / "android" / "app" / "build.gradle.kts",
]


def extract_sdk(text: str, name: str) -> int | None:
    patterns = [
        rf"\b{name}Version\s*[= ]\s*(\d+)",
        rf"\b{name}\s*[= ]\s*(\d+)",
    ]
    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            return int(match.group(1))
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="fail if generated Android project is absent")
    args = parser.parse_args()

    gradle = next((path for path in ANDROID_CANDIDATES if path.exists()), None)
    if gradle is None:
        message = "ANDROID_PROJECT_NOT_GENERATED: run Capacitor Android generation before store release"
        print(message)
        return 1 if args.strict else 0

    text = gradle.read_text(encoding="utf-8")
    compile_sdk = extract_sdk(text, "compileSdk")
    target_sdk = extract_sdk(text, "targetSdk")

    errors: list[str] = []
    if compile_sdk is None or compile_sdk < 36:
        errors.append(f"compileSdk must be >= 36 (found {compile_sdk!r})")
    if target_sdk is None or target_sdk < 36:
        errors.append(f"targetSdk must be >= 36 (found {target_sdk!r})")

    if errors:
        for error in errors:
            print(f"STORE_READINESS_FAIL: {error}")
        return 1

    print(f"STORE_READINESS_OK: {gradle.relative_to(ROOT)} compileSdk={compile_sdk} targetSdk={target_sdk}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
