"""Canonicalize Kraken native REST pair ids at terminal broker boundaries (v261).

Production on deployment 870221a321480c1584b39cc9f906980beaf8db61 proved
that ECEL correctly canonicalized ``XETHZUSD`` to ``ETH-USD`` and approved the
order, but the downstream Kraken broker path parsed the native REST id
generically as base ``XETHZ`` plus quote ``USD`` and produced ``XETHZ-USD``.
NIJA's own availability check then rejected that local synthetic symbol before
any order reached Kraken.

This patch repairs only that symbol-identity boundary.  Known Kraken REST pair
ids are translated to the existing NIJA standard symbols before terminal Kraken
broker validation.  The broker then uses the existing symbol mapper to translate
back to the exact Kraken pair id for submission.  Unknown symbols keep the
existing fail-closed behavior.

The exact local messages generated by NIJA's pre-submit Kraken symbol validation
are also registered with the already-installed rejection provenance classifiers
so those local outcomes cannot be mistaken for exchange hard rejections.
Existing rejection windows are never cleared.

No execution, writer, nonce, risk, kill-switch, capital, ECEL, min-notional,
ACK, fill, or activation gate is bypassed or fabricated.
"""
from __future__ import annotations

import logging
import os
import sys
import threading
import time
from functools import wraps
from types import ModuleType
from typing import Any, Callable

LOGGER = logging.getLogger("nija.runtime_kraken_terminal_symbol_canonicalization_v261")
MARKER = "20260828-kraken-terminal-symbol-canonicalization-v261"
_FLAG = "NIJA_KRAKEN_TERMINAL_SYMBOL_CANONICALIZATION_V261_READY"
_NORMALIZER_PATCH_ATTR = "_nija_kraken_terminal_symbol_normalizer_v261"
_ORDER_PATCH_ATTR = "_nija_kraken_terminal_order_symbol_v261"
_LOCK = threading.RLock()
_THREAD: threading.Thread | None = None

# Existing static Kraken map contains these legacy REST ids.  Keep the mapping
# explicit and narrow; it only changes identifiers, never tradability/rules.
_LEGACY_TO_STANDARD = {
    "XETHZUSD": "ETH-USD",
    "XXBTZUSD": "BTC-USD",
    "XXRPZUSD": "XRP-USD",
    "XETCZUSD": "ETC-USD",
    "XLTCZUSD": "LTC-USD",
    "XXLMZUSD": "XLM-USD",
    "XMLNZUSD": "MLN-USD",
    "XDGUSD": "DOGE-USD",
}

# These strings are emitted locally by NIJA before any Kraken AddOrder request.
# They therefore do not prove an exchange rejection and must not feed the
# exchange rejection-rate kill switch.
_LOCAL_SYMBOL_REJECT_MARKERS = (
    "not available on kraken",
    "kraken does not support symbol:",
    "kraken only supports usd/usdt pairs",
)


def _canonical_terminal_symbol(symbol: Any) -> str:
    raw = str(symbol or "").strip()
    if not raw:
        return raw
    compact = raw.upper().replace("-", "").replace("/", "")
    return _LEGACY_TO_STANDARD.get(compact, raw)


def _patch_normalizer(module: ModuleType) -> bool:
    current = getattr(module, "normalize_symbol_for_broker", None)
    if not callable(current):
        return True
    if getattr(current, _NORMALIZER_PATCH_ATTR, False):
        return True

    original: Callable[..., Any] = current

    @wraps(original)
    def normalize_symbol_for_broker_v261(symbol: str, broker_name: str) -> str:
        if str(broker_name or "").strip().lower() == "kraken":
            canonical = _canonical_terminal_symbol(symbol)
            if canonical != str(symbol or ""):
                try:
                    prior = original(symbol, broker_name)
                except Exception as exc:
                    prior = f"error:{type(exc).__name__}"
                LOGGER.critical(
                    "KRAKEN_TERMINAL_SYMBOL_V261_CANONICALIZED marker=%s surface=normalize_symbol_for_broker "
                    "raw=%s prior=%s canonical=%s symbol_identity_only=true safety_gates_bypassed=false",
                    MARKER,
                    str(symbol)[:64],
                    str(prior)[:64],
                    canonical[:64],
                )
                return canonical
        return original(symbol, broker_name)

    setattr(normalize_symbol_for_broker_v261, _NORMALIZER_PATCH_ATTR, True)
    setattr(normalize_symbol_for_broker_v261, "__wrapped__", original)
    setattr(module, "normalize_symbol_for_broker", normalize_symbol_for_broker_v261)
    return True


def _patch_order_surface(module: ModuleType, class_name: str) -> bool:
    cls = getattr(module, class_name, None)
    if not isinstance(cls, type):
        return True
    current = getattr(cls, "place_market_order", None)
    if not callable(current):
        return True
    if getattr(current, _ORDER_PATCH_ATTR, False):
        return True

    original: Callable[..., Any] = current

    @wraps(original)
    def place_market_order_v261(self: Any, symbol: str, *args: Any, **kwargs: Any) -> Any:
        canonical = _canonical_terminal_symbol(symbol)
        if canonical != str(symbol or ""):
            LOGGER.critical(
                "KRAKEN_TERMINAL_SYMBOL_V261_CANONICALIZED marker=%s surface=%s.place_market_order "
                "raw=%s canonical=%s symbol_identity_only=true ordinary_order_rules_unchanged=true "
                "execution_authority_unchanged=true nonce_policy_unchanged=true safety_gates_bypassed=false",
                MARKER,
                class_name,
                str(symbol)[:64],
                canonical[:64],
            )
        return original(self, canonical, *args, **kwargs)

    setattr(place_market_order_v261, _ORDER_PATCH_ATTR, True)
    setattr(place_market_order_v261, "__wrapped__", original)
    setattr(cls, "place_market_order", place_market_order_v261)
    return True


def _extend_classifier(module: ModuleType, attr: str) -> bool:
    current = getattr(module, attr, None)
    if not isinstance(current, tuple):
        return True
    additions = tuple(marker for marker in _LOCAL_SYMBOL_REJECT_MARKERS if marker not in current)
    if additions:
        setattr(module, attr, current + additions)
        LOGGER.critical(
            "KRAKEN_TERMINAL_SYMBOL_V261_LOCAL_REJECT_CLASSIFIER marker=%s module=%s attr=%s added=%s "
            "exchange_rejection_thresholds_unchanged=true rejection_window_cleared=false kill_switch_unchanged=true",
            MARKER,
            getattr(module, "__name__", "unknown"),
            attr,
            additions,
        )
    return True


def _patch_loaded() -> dict[str, bool]:
    outcomes: dict[str, bool] = {}
    seen: set[int] = set()

    for name, class_name in (
        ("bot.broker_manager", "KrakenBroker"),
        ("broker_manager", "KrakenBroker"),
        ("bot.broker_integration", "KrakenBrokerAdapter"),
        ("broker_integration", "KrakenBrokerAdapter"),
    ):
        module = sys.modules.get(name)
        if not isinstance(module, ModuleType) or id(module) in seen:
            continue
        seen.add(id(module))
        ok = _patch_order_surface(module, class_name)
        if class_name == "KrakenBroker":
            ok = _patch_normalizer(module) and ok
        outcomes[name] = ok

    classifier_targets = (
        ("nija_exchange_kill_switch_internal_reject_guard_patch", "_SOFT_NON_EXCHANGE_REASON_PATTERNS"),
        ("bot.exchange_kill_switch_internal_reject_guard_patch", "_SOFT_NON_EXCHANGE_REASON_PATTERNS"),
        ("bot.exchange_reject_dispatch_provenance_v228_patch", "_NON_EXCHANGE_MARKERS"),
        ("exchange_reject_dispatch_provenance_v228_patch", "_NON_EXCHANGE_MARKERS"),
        ("bot.exchange_kill_switch_alias_provenance_v258_patch", "_NON_EXCHANGE_MARKERS"),
        ("exchange_kill_switch_alias_provenance_v258_patch", "_NON_EXCHANGE_MARKERS"),
    )
    for name, attr in classifier_targets:
        module = sys.modules.get(name)
        if isinstance(module, ModuleType):
            outcomes[f"classifier:{name}"] = _extend_classifier(module, attr)

    return outcomes


def _self_test() -> bool:
    cases = {
        "XETHZUSD": "ETH-USD",
        "XETHZ-USD": "ETH-USD",
        "XXBTZUSD": "BTC-USD",
        "XXRPZUSD": "XRP-USD",
        "ETH-USD": "ETH-USD",
        "SOLUSD": "SOLUSD",
    }
    return all(_canonical_terminal_symbol(raw) == expected for raw, expected in cases.items())


def _worker() -> None:
    while True:
        try:
            _patch_loaded()
        except Exception as exc:
            LOGGER.warning(
                "KRAKEN_TERMINAL_SYMBOL_V261_REASSERT_ERROR marker=%s err=%s:%s trading_fail_closed=true",
                MARKER,
                type(exc).__name__,
                exc,
            )
        time.sleep(2.0)


def install() -> bool:
    global _THREAD
    tested = _self_test()
    outcomes = _patch_loaded()
    with _LOCK:
        if _THREAD is None or not _THREAD.is_alive():
            _THREAD = threading.Thread(
                target=_worker,
                name="KrakenTerminalSymbolCanonicalizationV261",
                daemon=True,
            )
            _THREAD.start()
    ready = bool(tested and _THREAD is not None and _THREAD.is_alive())
    os.environ[_FLAG] = "1" if ready else "0"
    if not ready:
        LOGGER.critical(
            "KRAKEN_TERMINAL_SYMBOL_V261_FAILED marker=%s self_test=%s outcomes=%s trading_fail_closed=true",
            MARKER,
            str(tested).lower(),
            outcomes,
        )
        return False
    LOGGER.critical(
        "KRAKEN_TERMINAL_SYMBOL_V261_READY marker=%s ready=true outcomes=%s "
        "legacy_rest_ids_to_standard=true broker_mapper_remains_authoritative=true "
        "local_symbol_validation_excluded_from_exchange_rejections=true rejection_window_cleared=false "
        "genuine_exchange_rejections_unchanged=true execution_authority_unchanged=true nonce_policy_unchanged=true "
        "risk_capital_killswitch_ecel_min_notional_order_fill_gates_unchanged=true execution_proof_fabricated=false "
        "forced_trade=false safety_gates_bypassed=false",
        MARKER,
        outcomes,
    )
    return True


def install_import_hook() -> bool:
    return install()


__all__ = [
    "MARKER",
    "install",
    "install_import_hook",
    "_canonical_terminal_symbol",
    "_patch_loaded",
    "_self_test",
]
